Update typescript to 4.7.4
inrupt/solid-client-access-grants-js pull request #276
Opened 2022-06-28 09:30 UTC by NSeydoux

This upgrades to the latest version of typescript, and fixes the mismatch in the fetch function signature it involves.

2022-06-28 14:09 UTC, matthieubosquet approved these changes
Updating TypeScript is fine, but you mixed it up with https://github.com/inrupt/solid-client-access-grants-js/pull/277/files.

Maybe remove the issueAccess* changes before merging?

2022-06-29 06:46 UTC, NSeydoux commented
Yeah #277 was required to pass e2e tests. I was planing on merging it first, and then rebase this on top.

2022-06-30 14:53 UTC, ThisIsMissEm requested changes
@NSeydoux I'm going to take this over, as we need to do the correct upgrade to the new eslint configs, so I'll push a commit with the changes required for that.

2022-06-30 14:53 UTC, ThisIsMissEm commented on package.json
>      "@inrupt/eslint-config-lib": "^1.0.0",
```suggestion
    "@inrupt/eslint-config-lib": "^1.0.0",
```

You no longer need `base` here.

2022-06-30 14:53 UTC, ThisIsMissEm commented on package.json
>      "@inrupt/eslint-config-lib": "^1.0.0",
Actually, ignore that. This repo hasn't been correctly upgraded to 1.0.0

2022-06-30 15:27 UTC, ThisIsMissEm commented
Okay, the Vercel crash here is related to the sourceurl plugin and typedoc 0.23.3, due to this breaking change:
> Removed ProjectReflection.files, this was an internal cache that should not have been exposed, and shouldn't have existed in the first place, since removing it made TypeDoc faster.

I'm going to remove the sourceurl plugin for now, as it was a "nice to have" on Vercel, but worked out of the box on the published docs.

2022-06-30 20:07 UTC, ThisIsMissEm approved these changes
I think this is now good to go.

2022-07-01 13:24 UTC, merged